enable_body_tracking:           False
enable_random_head_movement:    False
head_pan_joint:                 head_pan_joint
head_tilt_joint:                head_tilt_joint
#sound_effects_dir:              "../../resources/sounds/sound_effects"

